// <auto-generated />
using System;
using EnergyShare_v3.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyShare_v3.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406143802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.DataPartage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PartageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("VolumePartage_kWh")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("PartageId");

                    b.ToTable("data_partage", (string)null);
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.DemandeGRD", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgentTraitantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentaireReponseGRD")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReponse")
                        .HasColumnType("datetime2");

                    b.Property<string>("DemandeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("DemandeurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetailsDemande")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("OrganismePublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PartageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerimetreConfirme")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResponseStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgentTraitantId");

                    b.HasIndex("DemandeurId");

                    b.HasIndex("OrganismePublicId");

                    b.HasIndex("PartageId");

                    b.ToTable("demandes_grd", (string)null);
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.DocumentPartage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheminStockage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PartageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeDocument")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PartageId");

                    b.HasIndex("UploadedById");

                    b.ToTable("documents_partage", (string)null);
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.Matchs.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DistanceCalculee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("PointAccessAcheteurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PointAccessVendeurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PointAccessAcheteurId");

                    b.HasIndex("PointAccessVendeurId", "PointAccessAcheteurId")
                        .IsUnique();

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DestinataireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExpediteurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLu")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ObjetMessage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DestinataireId");

                    b.HasIndex("ExpediteurId");

                    b.HasIndex("MatchId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.OrganismePublic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("organismes_publics", (string)null);
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.Partages.Partage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EnergieType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("GestionnairePartageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Perimetre")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("VendeurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GestionnairePartageId");

                    b.HasIndex("VendeurId");

                    b.ToTable("partages", (string)null);
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.Partages.ParticipationPartage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCommunicationPreavis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSortiePlanifiee")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsInterlocuteurUnique")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PartageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PointAccessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserRolePartage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PointAccessId");

                    b.HasIndex("PartageId", "PointAccessId")
                        .IsUnique();

                    b.ToTable("participations_partage", (string)null);
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.PointAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AccordConsentement")
                        .HasColumnType("bit");

                    b.Property<string>("AdresseLine1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CodePostal")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("DateAccordConsentement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRetraitConsentement")
                        .HasColumnType("datetime2");

                    b.Property<string>("EAN_Encrypted")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Fournisseur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInjectionPoint")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("SmartMeter_Encrypted")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("point_accesses", (string)null);
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.ProfilsEnergie.ProfilEnergie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DemandeEnergie_kWh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("OffreEnergie_kWh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("PointAccessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PrixAchatCible_Eur")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PrixVenteCible_Eur")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("PointAccessId")
                        .IsUnique();

                    b.ToTable("profils_energie", (string)null);
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.TarifAccord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("PartageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PartageId");

                    b.ToTable("tarifs_accord", (string)null);
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroEntreprise")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid?>("OrganismePublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SocieteName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("OrganismePublicId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.DataPartage", b =>
                {
                    b.HasOne("EnergyShare_v3.Domain.Entities.Partages.Partage", "PartageEnergie")
                        .WithMany("RelevesSibelga")
                        .HasForeignKey("PartageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartageEnergie");
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.DemandeGRD", b =>
                {
                    b.HasOne("EnergyShare_v3.Domain.Entities.Users.User", "AgentTraitant")
                        .WithMany()
                        .HasForeignKey("AgentTraitantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnergyShare_v3.Domain.Entities.Users.User", "Demandeur")
                        .WithMany()
                        .HasForeignKey("DemandeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnergyShare_v3.Domain.Entities.OrganismePublic", "OrganismePublic")
                        .WithMany("DemandesGrd")
                        .HasForeignKey("OrganismePublicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnergyShare_v3.Domain.Entities.Partages.Partage", "Partage")
                        .WithMany("DemandesGrd")
                        .HasForeignKey("PartageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AgentTraitant");

                    b.Navigation("Demandeur");

                    b.Navigation("OrganismePublic");

                    b.Navigation("Partage");
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.DocumentPartage", b =>
                {
                    b.HasOne("EnergyShare_v3.Domain.Entities.Partages.Partage", "Partage")
                        .WithMany("Documents")
                        .HasForeignKey("PartageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnergyShare_v3.Domain.Entities.Users.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("EnergyShare_v3.Bricks.Model.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("DocumentPartageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DocumentPartageId");

                            b1.ToTable("documents_partage");

                            b1.WithOwner()
                                .HasForeignKey("DocumentPartageId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Partage");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.Matchs.Match", b =>
                {
                    b.HasOne("EnergyShare_v3.Domain.Entities.PointAccess", "PointAccessAcheteur")
                        .WithMany("MatchsAcheteurs")
                        .HasForeignKey("PointAccessAcheteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnergyShare_v3.Domain.Entities.PointAccess", "PointAccessVendeur")
                        .WithMany("MatchsVendeurs")
                        .HasForeignKey("PointAccessVendeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("EnergyShare_v3.Bricks.Model.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MatchId");

                            b1.ToTable("matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("PointAccessAcheteur");

                    b.Navigation("PointAccessVendeur");
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.Messages.Message", b =>
                {
                    b.HasOne("EnergyShare_v3.Domain.Entities.Users.User", "Destinataire")
                        .WithMany("MessagesRecus")
                        .HasForeignKey("DestinataireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnergyShare_v3.Domain.Entities.Users.User", "Expediteur")
                        .WithMany("MessagesEnvoyes")
                        .HasForeignKey("ExpediteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnergyShare_v3.Domain.Entities.Matchs.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Destinataire");

                    b.Navigation("Expediteur");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.OrganismePublic", b =>
                {
                    b.OwnsOne("EnergyShare_v3.Bricks.Model.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("OrganismePublicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrganismePublicId");

                            b1.ToTable("organismes_publics");

                            b1.WithOwner()
                                .HasForeignKey("OrganismePublicId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.Partages.Partage", b =>
                {
                    b.HasOne("EnergyShare_v3.Domain.Entities.Users.User", "GestionnairePartage")
                        .WithMany("PartagesGeres")
                        .HasForeignKey("GestionnairePartageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnergyShare_v3.Domain.Entities.Users.User", "Vendeur")
                        .WithMany("PartagesCrees")
                        .HasForeignKey("VendeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("EnergyShare_v3.Bricks.Model.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("PartageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PartageId");

                            b1.ToTable("partages");

                            b1.WithOwner()
                                .HasForeignKey("PartageId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("GestionnairePartage");

                    b.Navigation("Vendeur");
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.Partages.ParticipationPartage", b =>
                {
                    b.HasOne("EnergyShare_v3.Domain.Entities.Partages.Partage", "Partage")
                        .WithMany("Membres")
                        .HasForeignKey("PartageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnergyShare_v3.Domain.Entities.PointAccess", "PointAccess")
                        .WithMany("Membres")
                        .HasForeignKey("PointAccessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("EnergyShare_v3.Bricks.Model.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("ParticipationPartageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ParticipationPartageId");

                            b1.ToTable("participations_partage");

                            b1.WithOwner()
                                .HasForeignKey("ParticipationPartageId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Partage");

                    b.Navigation("PointAccess");
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.PointAccess", b =>
                {
                    b.HasOne("EnergyShare_v3.Domain.Entities.Users.User", "User")
                        .WithMany("PointsAccess")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("EnergyShare_v3.Bricks.Model.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("PointAccessId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PointAccessId");

                            b1.ToTable("point_accesses");

                            b1.WithOwner()
                                .HasForeignKey("PointAccessId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.ProfilsEnergie.ProfilEnergie", b =>
                {
                    b.HasOne("EnergyShare_v3.Domain.Entities.PointAccess", "PointAccess")
                        .WithOne("ProfilEnergie")
                        .HasForeignKey("EnergyShare_v3.Domain.Entities.ProfilsEnergie.ProfilEnergie", "PointAccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EnergyShare_v3.Bricks.Model.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("ProfilEnergieId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProfilEnergieId");

                            b1.ToTable("profils_energie");

                            b1.WithOwner()
                                .HasForeignKey("ProfilEnergieId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("PointAccess");
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.TarifAccord", b =>
                {
                    b.HasOne("EnergyShare_v3.Domain.Entities.Partages.Partage", "Partage")
                        .WithMany("TarifsAccord")
                        .HasForeignKey("PartageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EnergyShare_v3.Bricks.Model.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("TarifAccordId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TarifAccordId");

                            b1.ToTable("tarifs_accord");

                            b1.WithOwner()
                                .HasForeignKey("TarifAccordId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Partage");
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("EnergyShare_v3.Domain.Entities.OrganismePublic", "OrganismePublic")
                        .WithMany("Employes")
                        .HasForeignKey("OrganismePublicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("EnergyShare_v3.Bricks.Model.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("EnergyShare_v3.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("OrganismePublic");
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.OrganismePublic", b =>
                {
                    b.Navigation("DemandesGrd");

                    b.Navigation("Employes");
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.Partages.Partage", b =>
                {
                    b.Navigation("DemandesGrd");

                    b.Navigation("Documents");

                    b.Navigation("Membres");

                    b.Navigation("RelevesSibelga");

                    b.Navigation("TarifsAccord");
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.PointAccess", b =>
                {
                    b.Navigation("MatchsAcheteurs");

                    b.Navigation("MatchsVendeurs");

                    b.Navigation("Membres");

                    b.Navigation("ProfilEnergie");
                });

            modelBuilder.Entity("EnergyShare_v3.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("MessagesEnvoyes");

                    b.Navigation("MessagesRecus");

                    b.Navigation("PartagesCrees");

                    b.Navigation("PartagesGeres");

                    b.Navigation("PointsAccess");
                });
#pragma warning restore 612, 618
        }
    }
}
